version: '3.9'
services:
  head:
    build: &build-definition
      context: .
      dockerfile: Dockerfile
    image: trinity
    container_name: head
    ports:
      - "7000:7000"
    command: dotnet run --no-build --project DistributedHashtable/DHT.GE.Server -- head:7000,node1:7001,node2:7002
    depends_on:
      # Need to run node2 and node2 before starting the head cluster node.
      - node1
      - node2
  node1:
    image: trinity
    container_name: node1
    ports:
      - "7001:7001"
    command: dotnet run --no-build --project DistributedHashtable/DHT.GE.Server -- node1:7001
  node2:
    image: trinity
    container_name: node2
    ports:
      - "7002:7002"
    command: dotnet run --no-build --project DistributedHashtable/DHT.GE.Server -- node2:7002
